/**
 * Seat Inventory Generator for BookMyShow Clone (Phase 4.4)
 * Generates seat inventory with individual statuses, dynamic tier prices, and accessibility flags.
 */

/**
 * Generates complete seat inventory for a show based on the screen's physical layout
 * or standard fallback layout.
 *
 * @param {object} screen - Screen subdocument from Theater model
 * @param {object} pricingSnapshot - Dynamic pricing snapshot generated by pricingEngine
 * @param {number} basePrice - Fallback base price
 * @returns {Array<object>} seats inventory
 */
export const generateSeatInventory = (screen, pricingSnapshot, basePrice = 200) => {
  const tierPrices = pricingSnapshot?.tierPrices || {
    Standard: basePrice,
    Premium: Math.round(basePrice * 1.25),
    VIP: Math.round(basePrice * 1.5),
    Accessible: basePrice,
  };

  // 1. If screen has a pre-configured physical seat layout from Phase 4.3 Visual Builder
  if (screen?.seatLayout?.seats && screen.seatLayout.seats.length > 0) {
    return screen.seatLayout.seats.map((seat) => {
      const tier = seat.tier || 'Standard';
      const seatPrice = tierPrices[tier] || tierPrices.Standard || basePrice;

      return {
        seatNumber: seat.seatNumber,
        row: seat.row,
        number: seat.number,
        tier,
        price: seatPrice,
        priceMultiplier: seat.priceMultiplier || 1.0,
        isAccessible: Boolean(seat.isAccessible),
        status: 'available',
      };
    });
  }

  // 2. Fallback to standard 100-seat auditorium layout (Rows A–J, 10 seats/row)
  const rows = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
  const seatsPerRow = 10;
  const inventory = [];

  for (const row of rows) {
    let tier = 'Standard';
    if (['A', 'B'].includes(row)) {
      tier = 'VIP';
    } else if (['C', 'D', 'E', 'F'].includes(row)) {
      tier = 'Premium';
    }

    const price = tierPrices[tier] || tierPrices.Standard || basePrice;

    for (let num = 1; num <= seatsPerRow; num++) {
      inventory.push({
        seatNumber: `${row}${num}`,
        row,
        number: num,
        tier,
        price,
        priceMultiplier: tier === 'VIP' ? 1.5 : tier === 'Premium' ? 1.25 : 1.0,
        isAccessible: row === 'J' && (num === 1 || num === seatsPerRow), // Accessible end seats on back row
        status: 'available',
      });
    }
  }

  return inventory;
};

export default {
  generateSeatInventory,
};
