import mongoose from 'mongoose';

/**
 * Embedded Seat Schema for individual show layout and booking state
 */
const seatSchema = new mongoose.Schema(
  {
    seatNumber: {
      type: String,
      required: [true, 'Seat number is required'],
      trim: true,
    },
    row: {
      type: String,
      required: [true, 'Row identifier is required'],
      trim: true,
    },
    number: {
      type: Number,
    },
    status: {
      type: String,
      enum: {
        values: ['available', 'booked', 'locked'],
        message: '{VALUE} is not a valid seat status',
      },
      default: 'available',
    },
    tier: {
      type: String,
      enum: ['Standard', 'Premium', 'VIP', 'Accessible'],
      default: 'Standard',
    },
    price: {
      type: Number,
      default: 200,
    },
    priceMultiplier: {
      type: Number,
      default: 1.0,
    },
    isAccessible: {
      type: Boolean,
      default: false,
    },
  },
  {
    _id: false,
  }
);

/**
 * Show Schema definition for BookMyShow Clone (Phase 4.4 Show Scheduling Upgrade)
 */
const showSchema = new mongoose.Schema(
  {
    movie: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Movie',
      required: [true, 'Movie reference is required'],
      index: true,
    },
    theater: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Theater',
      required: [true, 'Theater reference is required'],
      index: true,
    },
    screen: {
      type: Number,
      required: [true, 'Screen number is required'],
      min: [1, 'Screen number must be at least 1'],
    },
    screenId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
    },
    screenName: {
      type: String,
      trim: true,
      default: 'Screen 1',
    },
    screenType: {
      type: String,
      enum: [
        'IMAX',
        'Dolby Atmos',
        '4DX',
        'Standard',
        'Gold Class',
        'ScreenX',
        'IMAX 3D',
        'Laser',
        'ICE Immersive',
      ],
      default: 'Standard',
    },
    showTime: {
      type: Date,
      required: [true, 'Show time is required'],
      index: true,
    },
    startTime: {
      type: Date,
      index: true,
    },
    endTime: {
      type: Date,
      index: true,
    },
    movieDuration: {
      type: Number,
      default: 120, // Duration in minutes
    },
    trailerBuffer: {
      type: Number,
      default: 15, // Trailers & commercials buffer in minutes
    },
    cleaningBuffer: {
      type: Number,
      default: 20, // Auditorium cleaning & preparation buffer in minutes
    },
    price: {
      type: Number,
      required: [true, 'Ticket price is required'],
      min: [0, 'Ticket price cannot be negative'],
    },
    pricingSnapshot: {
      basePrice: { type: Number, default: 200 },
      timeSlot: { type: String, default: 'Evening' },
      timeMultiplier: { type: Number, default: 1.0 },
      screenType: { type: String, default: 'Standard' },
      screenMultiplier: { type: Number, default: 1.0 },
      tierPrices: {
        Standard: { type: Number, default: 200 },
        Premium: { type: Number, default: 250 },
        VIP: { type: Number, default: 300 },
        Accessible: { type: Number, default: 200 },
      },
    },
    recurringGroupId: {
      type: String,
      default: null,
      index: true,
    },
    status: {
      type: String,
      enum: ['scheduled', 'live', 'completed', 'cancelled'],
      default: 'scheduled',
      index: true,
    },
    seats: {
      type: [seatSchema],
      default: [],
    },
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
    deletedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Synchronize startTime, showTime, and endTime before saving
showSchema.pre('save', function (next) {
  if (this.startTime && !this.showTime) {
    this.showTime = this.startTime;
  } else if (this.showTime && !this.startTime) {
    this.startTime = this.showTime;
  }

  if (this.startTime && !this.endTime) {
    const totalMinutes =
      (this.movieDuration || 120) + (this.trailerBuffer || 15) + (this.cleaningBuffer || 20);
    this.endTime = new Date(new Date(this.startTime).getTime() + totalMinutes * 60 * 1000);
  }

  next();
});

// Virtual for real-time occupancy statistics
showSchema.virtual('occupancy').get(function () {
  const total = this.seats?.length || 0;
  const booked = this.seats?.filter((s) => s.status === 'booked').length || 0;
  const percentage = total > 0 ? Math.round((booked / total) * 100) : 0;
  return {
    totalSeats: total,
    bookedSeats: booked,
    percentage,
  };
});

// Virtual for total revenue generated by booked seats
showSchema.virtual('revenue').get(function () {
  const bookedSeats = this.seats?.filter((s) => s.status === 'booked') || [];
  const total = bookedSeats.reduce((sum, s) => sum + (s.price || this.price || 200), 0);
  return {
    total,
    currency: 'INR',
  };
});

// Compound indexes for high-throughput conflict detection and scheduling queries
showSchema.index({ theater: 1, screen: 1, startTime: 1, endTime: 1 });
showSchema.index({ theater: 1, screenId: 1, startTime: 1, endTime: 1 });
showSchema.index({ theater: 1, showTime: 1 });
showSchema.index({ movie: 1, showTime: 1 });

export default mongoose.model('Show', showSchema);
